package https.wsaahomo_afip_gov_ar.ws.services.logincms;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.4.2
 * 2020-01-29T12:30:44.771-03:00
 * Generated source version: 2.4.2
 * 
 */
@WebService(targetNamespace = "https://wsaahomo.afip.gov.ar/ws/services/LoginCms", name = "LoginCMS")
@XmlSeeAlso({ObjectFactory.class, gov.afip.desein.dvadac.sua.view.wsaa.ObjectFactory.class})
public interface LoginCMS {

    @WebMethod
    @RequestWrapper(localName = "loginCms", targetNamespace = "http://wsaa.view.sua.dvadac.desein.afip.gov", className = "gov.afip.desein.dvadac.sua.view.wsaa.LoginCms")
    @ResponseWrapper(localName = "loginCmsResponse", targetNamespace = "http://wsaa.view.sua.dvadac.desein.afip.gov", className = "gov.afip.desein.dvadac.sua.view.wsaa.LoginCmsResponse")
    @WebResult(name = "loginCmsReturn", targetNamespace = "http://wsaa.view.sua.dvadac.desein.afip.gov")
    public java.lang.String loginCms(
        @WebParam(name = "in0", targetNamespace = "http://wsaa.view.sua.dvadac.desein.afip.gov")
        java.lang.String in0
    ) throws LoginFault_Exception;
}
