package https.wsaahomo_afip_gov_ar.ws.services.logincms;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.4.2
 * 2020-01-29T12:30:44.792-03:00
 * Generated source version: 2.4.2
 * 
 */
@WebServiceClient(name = "LoginCMSService", 
                  wsdlLocation = "file:/C:/Users/l0692115/Desktop/inicio/wsaa/src/main/resources/wsdl/login.xml",
                  targetNamespace = "https://wsaahomo.afip.gov.ar/ws/services/LoginCms") 
public class LoginCMSService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("https://wsaahomo.afip.gov.ar/ws/services/LoginCms", "LoginCMSService");
    public final static QName LoginCms = new QName("https://wsaahomo.afip.gov.ar/ws/services/LoginCms", "LoginCms");
    static {
        URL url = null;
        try {
            url = new URL("file:/C:/Users/l0692115/Desktop/inicio/wsaa/src/main/resources/wsdl/login.xml");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(LoginCMSService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "file:/C:/Users/l0692115/Desktop/inicio/wsaa/src/main/resources/wsdl/login.xml");
        }
        WSDL_LOCATION = url;
    }

    public LoginCMSService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public LoginCMSService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public LoginCMSService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public LoginCMSService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public LoginCMSService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public LoginCMSService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     *
     * @return
     *     returns LoginCMS
     */
    @WebEndpoint(name = "LoginCms")
    public LoginCMS getLoginCms() {
        return super.getPort(LoginCms, LoginCMS.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns LoginCMS
     */
    @WebEndpoint(name = "LoginCms")
    public LoginCMS getLoginCms(WebServiceFeature... features) {
        return super.getPort(LoginCms, LoginCMS.class, features);
    }

}
