
package https.wsaahomo_afip_gov_ar.ws.services.logincms;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 2.4.2
 * 2020-01-29T12:30:44.745-03:00
 * Generated source version: 2.4.2
 */

@WebFault(name = "fault", targetNamespace = "https://wsaahomo.afip.gov.ar/ws/services/LoginCms")
public class LoginFault_Exception extends Exception {
    
    private https.wsaahomo_afip_gov_ar.ws.services.logincms.LoginFault fault;

    public LoginFault_Exception() {
        super();
    }
    
    public LoginFault_Exception(String message) {
        super(message);
    }
    
    public LoginFault_Exception(String message, Throwable cause) {
        super(message, cause);
    }

    public LoginFault_Exception(String message, https.wsaahomo_afip_gov_ar.ws.services.logincms.LoginFault fault) {
        super(message);
        this.fault = fault;
    }

    public LoginFault_Exception(String message, https.wsaahomo_afip_gov_ar.ws.services.logincms.LoginFault fault, Throwable cause) {
        super(message, cause);
        this.fault = fault;
    }

    public https.wsaahomo_afip_gov_ar.ws.services.logincms.LoginFault getFaultInfo() {
        return this.fault;
    }
}
